repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/life4/flakehell.git
    rev: v.0.8.0
    hooks:
      - id: flakehell
        language_version: python3
  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.23
    hooks:
      - id: conform
        stages:
          - commit-msg
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-aws-credentials
        args: [
            "--allow-missing-credentials"
        ]
      - id: detect-private-key
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        files: custom_components/*.py